
CREATE DATABASE REACTLOGIN2
GO

USE REACTLOGIN2
GO

CREATE TABLE Users
(
	username varchar(10) NOT NULL,
	passwords varchar(10) NOT NULL,
	email varchar(30) NOT NULL,
	follows INT DEFAULT 0
)

CREATE TABLE WRITE_CONTENT
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	WRITERS VARCHAR(10) NOT NULL,
	TITLES VARCHAR(800) NOT NULL,
	HASHTAGS VARCHAR(800) NOT NULL,
	CONTENTS VARCHAR(5000) NOT NULL,
	LIKES INT DEFAULT 0,
	CREATE_AT DATETIME DEFAULT GETDATE()
)

CREATE TABLE LIKE_BLOG
(
	LIKE_ID INT PRIMARY KEY IDENTITY(1,1),
	ID INT NOT NULL,
	username varchar(10) NOT NULL
)

CREATE TABLE FOLLOW
(
	FOLLOWER VARCHAR(10) NOT NULL,
	BE_FOLLOWED VARCHAR(10) NOT NULL
)
CREATE TABLE COMMENT
(
	COMMENT_ID INT PRIMARY KEY IDENTITY(1,1),
	COMMENT VARCHAR(3000),
	USERS VARCHAR(10) NOT NULL,
	ID INT NOT NULL,
	COMMENT_AT DATETIME DEFAULT GETDATE()
)

ALTER TABLE Users ADD PRIMARY KEY (username)

ALTER TABLE WRITE_CONTENT ADD CONSTRAINT FK_UsersWRITE_CONTENT FOREIGN KEY (WRITERS) REFERENCES Users(username)

ALTER TABLE LIKE_BLOG ADD CONSTRAINT FK_ID FOREIGN KEY (ID) REFERENCES WRITE_CONTENT(ID)

ALTER TABLE LIKE_BLOG ADD CONSTRAINT FK_username FOREIGN KEY (username) REFERENCES Users(username)

ALTER TABLE FOLLOW ADD CONSTRAINT PK_FOLLOWER_BE_FOLLOWED PRIMARY KEY (FOLLOWER, BE_FOLLOWED)

ALTER TABLE FOLLOW ADD CONSTRAINT FK_FOLLOWER_Users FOREIGN KEY (FOLLOWER) REFERENCES Users (username)

ALTER TABLE FOLLOW ADD CONSTRAINT FK_FOLLOWED_Users FOREIGN KEY (BE_FOLLOWED) REFERENCES Users (username)

ALTER TABLE COMMENT ADD CONSTRAINT FK_USERS_Users FOREIGN KEY (USERS) REFERENCES Users (username)

ALTER TABLE COMMENT ADD CONSTRAINT FK_ID_WRITE_CONTENT FOREIGN KEY (ID) REFERENCES WRITE_CONTENT (ID)

